extern const GeoLayout sofia_Mouth1[];
extern const GeoLayout sofia_Mouth2[];
extern const GeoLayout sofia_Mouth3[];
extern const GeoLayout sofia_Mouth4[];
extern const GeoLayout sofia_Mouth5[];
extern const GeoLayout sofia_Mouth6[];
extern const GeoLayout sofia_Mouth7[];
extern const GeoLayout sofia_Head_Left[];
extern const GeoLayout sofia_Head_Right[];
extern const GeoLayout sofia_Head_Up[];
extern const GeoLayout sofia_Head_Down[];
extern const GeoLayout sofia_Head_Dead[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Left[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Right[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Up[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Down[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Dead[];
extern const GeoLayout sofia_Capless_Head[];
extern const GeoLayout sofia_Left_Hand_Open[];
extern const GeoLayout sofia_Left_Hand_Peace[];
extern const GeoLayout sofia_Right_Hand_Open[];
extern const GeoLayout sofia_Right_Hand_Peace[];
extern const GeoLayout sofia_Right_Hand_Cap[];
extern const GeoLayout sofia_Right_Hand_Wing_Cap[];
extern const GeoLayout sofia_Mouth1_opt_1[];
extern const GeoLayout sofia_Mouth2_opt_1[];
extern const GeoLayout sofia_Mouth3_opt_1[];
extern const GeoLayout sofia_Mouth4_opt_1[];
extern const GeoLayout sofia_Mouth5_opt_1[];
extern const GeoLayout sofia_Mouth6_opt_1[];
extern const GeoLayout sofia_Mouth7_opt_1[];
extern const GeoLayout sofia_geo_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_2[];
extern const GeoLayout sofia_Mouth2_opt_2[];
extern const GeoLayout sofia_Mouth3_opt_2[];
extern const GeoLayout sofia_Mouth4_opt_2[];
extern const GeoLayout sofia_Mouth5_opt_2[];
extern const GeoLayout sofia_Mouth6_opt_2[];
extern const GeoLayout sofia_Mouth7_opt_2[];
extern const GeoLayout sofia_geo_opt_2[];
extern const GeoLayout sofia_Mouth1_opt_1_1[];
extern const GeoLayout sofia_Mouth2_opt_1_1[];
extern const GeoLayout sofia_Mouth3_opt_1_1[];
extern const GeoLayout sofia_Mouth4_opt_1_1[];
extern const GeoLayout sofia_Mouth5_opt_1_1[];
extern const GeoLayout sofia_Mouth6_opt_1_1[];
extern const GeoLayout sofia_Mouth7_opt_1_1[];
extern const GeoLayout sofia_geo_opt_1_1[];
extern const GeoLayout sofia_Mouth1_opt_2_1[];
extern const GeoLayout sofia_Mouth2_opt_2_1[];
extern const GeoLayout sofia_Mouth3_opt_2_1[];
extern const GeoLayout sofia_Mouth4_opt_2_1[];
extern const GeoLayout sofia_Mouth5_opt_2_1[];
extern const GeoLayout sofia_Mouth6_opt_2_1[];
extern const GeoLayout sofia_Mouth7_opt_2_1[];
extern const GeoLayout sofia_geo_opt_2_1[];
extern const GeoLayout sofia_geo_opt_1_2[];
extern const GeoLayout sofia_geo_opt_1_3[];
extern const GeoLayout sofia_Mouth1_opt_1_2[];
extern const GeoLayout sofia_Mouth2_opt_1_2[];
extern const GeoLayout sofia_Mouth3_opt_1_2[];
extern const GeoLayout sofia_Mouth4_opt_1_2[];
extern const GeoLayout sofia_Mouth5_opt_1_2[];
extern const GeoLayout sofia_Mouth6_opt_1_2[];
extern const GeoLayout sofia_Mouth7_opt_1_2[];
extern const GeoLayout sofia_Mouth1_opt_1_opt_1[];
extern const GeoLayout sofia_Mouth2_opt_1_opt_1[];
extern const GeoLayout sofia_Mouth3_opt_1_opt_1[];
extern const GeoLayout sofia_Mouth4_opt_1_opt_1[];
extern const GeoLayout sofia_Mouth5_opt_1_opt_1[];
extern const GeoLayout sofia_Mouth6_opt_1_opt_1[];
extern const GeoLayout sofia_Mouth7_opt_1_opt_1[];
extern const GeoLayout sofia_geo_opt_1_4_opt_1_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_1_opt_2[];
extern const GeoLayout sofia_Mouth2_opt_1_opt_2[];
extern const GeoLayout sofia_Mouth3_opt_1_opt_2[];
extern const GeoLayout sofia_Mouth4_opt_1_opt_2[];
extern const GeoLayout sofia_Mouth5_opt_1_opt_2[];
extern const GeoLayout sofia_Mouth6_opt_1_opt_2[];
extern const GeoLayout sofia_Mouth7_opt_1_opt_2[];
extern const GeoLayout sofia_geo_opt_1_4_opt_1_opt_2[];
extern const GeoLayout sofia_Head_Left_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_1_3[];
extern const GeoLayout sofia_Mouth2_opt_1_3[];
extern const GeoLayout sofia_Mouth3_opt_1_3[];
extern const GeoLayout sofia_Mouth4_opt_1_3[];
extern const GeoLayout sofia_Mouth5_opt_1_3[];
extern const GeoLayout sofia_Mouth6_opt_1_3[];
extern const GeoLayout sofia_Mouth7_opt_1_3[];
extern const GeoLayout sofia_Head_Right_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_1_4[];
extern const GeoLayout sofia_Mouth2_opt_1_4[];
extern const GeoLayout sofia_Mouth3_opt_1_4[];
extern const GeoLayout sofia_Mouth4_opt_1_4[];
extern const GeoLayout sofia_Mouth5_opt_1_4[];
extern const GeoLayout sofia_Mouth6_opt_1_4[];
extern const GeoLayout sofia_Mouth7_opt_1_4[];
extern const GeoLayout sofia_Head_Up_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_1_5[];
extern const GeoLayout sofia_Mouth2_opt_1_5[];
extern const GeoLayout sofia_Mouth3_opt_1_5[];
extern const GeoLayout sofia_Mouth4_opt_1_5[];
extern const GeoLayout sofia_Mouth5_opt_1_5[];
extern const GeoLayout sofia_Mouth6_opt_1_5[];
extern const GeoLayout sofia_Mouth7_opt_1_5[];
extern const GeoLayout sofia_Head_Down_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_1_6[];
extern const GeoLayout sofia_Mouth2_opt_1_6[];
extern const GeoLayout sofia_Mouth3_opt_1_6[];
extern const GeoLayout sofia_Mouth4_opt_1_6[];
extern const GeoLayout sofia_Mouth5_opt_1_6[];
extern const GeoLayout sofia_Mouth6_opt_1_6[];
extern const GeoLayout sofia_Mouth7_opt_1_6[];
extern const GeoLayout sofia_Head_Dead_opt_1[];
extern const GeoLayout sofia_Capless_Head_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_1_7[];
extern const GeoLayout sofia_Mouth2_opt_1_7[];
extern const GeoLayout sofia_Mouth3_opt_1_7[];
extern const GeoLayout sofia_Mouth4_opt_1_7[];
extern const GeoLayout sofia_Mouth5_opt_1_7[];
extern const GeoLayout sofia_Mouth6_opt_1_7[];
extern const GeoLayout sofia_Mouth7_opt_1_7[];
extern const GeoLayout sofia_geo_opt_1_1_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_1_1_opt_1[];
extern const GeoLayout sofia_Mouth2_opt_1_1_opt_1[];
extern const GeoLayout sofia_Mouth3_opt_1_1_opt_1[];
extern const GeoLayout sofia_Mouth4_opt_1_1_opt_1[];
extern const GeoLayout sofia_Mouth5_opt_1_1_opt_1[];
extern const GeoLayout sofia_Mouth6_opt_1_1_opt_1[];
extern const GeoLayout sofia_Mouth7_opt_1_1_opt_1[];
extern const GeoLayout sofia_geo_opt_2_1_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_2_1_opt_1[];
extern const GeoLayout sofia_Mouth2_opt_2_1_opt_1[];
extern const GeoLayout sofia_Mouth3_opt_2_1_opt_1[];
extern const GeoLayout sofia_Mouth4_opt_2_1_opt_1[];
extern const GeoLayout sofia_Mouth5_opt_2_1_opt_1[];
extern const GeoLayout sofia_Mouth6_opt_2_1_opt_1[];
extern const GeoLayout sofia_Mouth7_opt_2_1_opt_1[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Left_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_1_8[];
extern const GeoLayout sofia_Mouth2_opt_1_8[];
extern const GeoLayout sofia_Mouth3_opt_1_8[];
extern const GeoLayout sofia_Mouth4_opt_1_8[];
extern const GeoLayout sofia_Mouth5_opt_1_8[];
extern const GeoLayout sofia_Mouth6_opt_1_8[];
extern const GeoLayout sofia_Mouth7_opt_1_8[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Right_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_1_9[];
extern const GeoLayout sofia_Mouth2_opt_1_9[];
extern const GeoLayout sofia_Mouth3_opt_1_9[];
extern const GeoLayout sofia_Mouth4_opt_1_9[];
extern const GeoLayout sofia_Mouth5_opt_1_9[];
extern const GeoLayout sofia_Mouth6_opt_1_9[];
extern const GeoLayout sofia_Mouth7_opt_1_9[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Up_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_1_10[];
extern const GeoLayout sofia_Mouth2_opt_1_10[];
extern const GeoLayout sofia_Mouth3_opt_1_10[];
extern const GeoLayout sofia_Mouth4_opt_1_10[];
extern const GeoLayout sofia_Mouth5_opt_1_10[];
extern const GeoLayout sofia_Mouth6_opt_1_10[];
extern const GeoLayout sofia_Mouth7_opt_1_10[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Down_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_1_11[];
extern const GeoLayout sofia_Mouth2_opt_1_11[];
extern const GeoLayout sofia_Mouth3_opt_1_11[];
extern const GeoLayout sofia_Mouth4_opt_1_11[];
extern const GeoLayout sofia_Mouth5_opt_1_11[];
extern const GeoLayout sofia_Mouth6_opt_1_11[];
extern const GeoLayout sofia_Mouth7_opt_1_11[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Dead_opt_1[];
extern const GeoLayout sofia_geo_opt_1_4_opt_1_opt_1_1[];
extern const GeoLayout sofia_geo_opt_1_4_opt_1_opt_1_2[];
extern const GeoLayout sofia_Left_Hand_Open_opt_1[];
extern const GeoLayout sofia_Left_Hand_Peace_opt_1[];
extern const GeoLayout sofia_Left_Hand_Open_opt_1_1[];
extern const GeoLayout sofia_Right_Hand_Open_opt_1[];
extern const GeoLayout sofia_Right_Hand_Peace_opt_1[];
extern const GeoLayout sofia_Right_Hand_Cap_opt_1[];
extern const GeoLayout sofia_Right_Hand_Wing_Cap_opt_1[];
extern const GeoLayout sofia_geo_opt_1_4[];
extern const GeoLayout sofia_Mouth1_opt_2_2[];
extern const GeoLayout sofia_Mouth2_opt_2_2[];
extern const GeoLayout sofia_Mouth3_opt_2_2[];
extern const GeoLayout sofia_Mouth4_opt_2_2[];
extern const GeoLayout sofia_Mouth5_opt_2_2[];
extern const GeoLayout sofia_Mouth6_opt_2_2[];
extern const GeoLayout sofia_Mouth7_opt_2_2[];
extern const GeoLayout sofia_Mouth1_opt_2_opt_1[];
extern const GeoLayout sofia_Mouth2_opt_2_opt_1[];
extern const GeoLayout sofia_Mouth3_opt_2_opt_1[];
extern const GeoLayout sofia_Mouth4_opt_2_opt_1[];
extern const GeoLayout sofia_Mouth5_opt_2_opt_1[];
extern const GeoLayout sofia_Mouth6_opt_2_opt_1[];
extern const GeoLayout sofia_Mouth7_opt_2_opt_1[];
extern const GeoLayout sofia_geo_opt_2_2_opt_2_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_2_opt_2[];
extern const GeoLayout sofia_Mouth2_opt_2_opt_2[];
extern const GeoLayout sofia_Mouth3_opt_2_opt_2[];
extern const GeoLayout sofia_Mouth4_opt_2_opt_2[];
extern const GeoLayout sofia_Mouth5_opt_2_opt_2[];
extern const GeoLayout sofia_Mouth6_opt_2_opt_2[];
extern const GeoLayout sofia_Mouth7_opt_2_opt_2[];
extern const GeoLayout sofia_geo_opt_2_2_opt_2_opt_2[];
extern const GeoLayout sofia_Head_Left_opt_2[];
extern const GeoLayout sofia_Mouth1_opt_2_3[];
extern const GeoLayout sofia_Mouth2_opt_2_3[];
extern const GeoLayout sofia_Mouth3_opt_2_3[];
extern const GeoLayout sofia_Mouth4_opt_2_3[];
extern const GeoLayout sofia_Mouth5_opt_2_3[];
extern const GeoLayout sofia_Mouth6_opt_2_3[];
extern const GeoLayout sofia_Mouth7_opt_2_3[];
extern const GeoLayout sofia_Head_Right_opt_2[];
extern const GeoLayout sofia_Mouth1_opt_2_4[];
extern const GeoLayout sofia_Mouth2_opt_2_4[];
extern const GeoLayout sofia_Mouth3_opt_2_4[];
extern const GeoLayout sofia_Mouth4_opt_2_4[];
extern const GeoLayout sofia_Mouth5_opt_2_4[];
extern const GeoLayout sofia_Mouth6_opt_2_4[];
extern const GeoLayout sofia_Mouth7_opt_2_4[];
extern const GeoLayout sofia_Head_Up_opt_2[];
extern const GeoLayout sofia_Mouth1_opt_2_5[];
extern const GeoLayout sofia_Mouth2_opt_2_5[];
extern const GeoLayout sofia_Mouth3_opt_2_5[];
extern const GeoLayout sofia_Mouth4_opt_2_5[];
extern const GeoLayout sofia_Mouth5_opt_2_5[];
extern const GeoLayout sofia_Mouth6_opt_2_5[];
extern const GeoLayout sofia_Mouth7_opt_2_5[];
extern const GeoLayout sofia_Head_Down_opt_2[];
extern const GeoLayout sofia_Mouth1_opt_2_6[];
extern const GeoLayout sofia_Mouth2_opt_2_6[];
extern const GeoLayout sofia_Mouth3_opt_2_6[];
extern const GeoLayout sofia_Mouth4_opt_2_6[];
extern const GeoLayout sofia_Mouth5_opt_2_6[];
extern const GeoLayout sofia_Mouth6_opt_2_6[];
extern const GeoLayout sofia_Mouth7_opt_2_6[];
extern const GeoLayout sofia_Head_Dead_opt_2[];
extern const GeoLayout sofia_Capless_Head_opt_2[];
extern const GeoLayout sofia_Mouth1_opt_2_7[];
extern const GeoLayout sofia_Mouth2_opt_2_7[];
extern const GeoLayout sofia_Mouth3_opt_2_7[];
extern const GeoLayout sofia_Mouth4_opt_2_7[];
extern const GeoLayout sofia_Mouth5_opt_2_7[];
extern const GeoLayout sofia_Mouth6_opt_2_7[];
extern const GeoLayout sofia_Mouth7_opt_2_7[];
extern const GeoLayout sofia_geo_opt_1_1_opt_2[];
extern const GeoLayout sofia_Mouth1_opt_1_1_opt_2[];
extern const GeoLayout sofia_Mouth2_opt_1_1_opt_2[];
extern const GeoLayout sofia_Mouth3_opt_1_1_opt_2[];
extern const GeoLayout sofia_Mouth4_opt_1_1_opt_2[];
extern const GeoLayout sofia_Mouth5_opt_1_1_opt_2[];
extern const GeoLayout sofia_Mouth6_opt_1_1_opt_2[];
extern const GeoLayout sofia_Mouth7_opt_1_1_opt_2[];
extern const GeoLayout sofia_geo_opt_2_1_opt_2[];
extern const GeoLayout sofia_Mouth1_opt_2_1_opt_2[];
extern const GeoLayout sofia_Mouth2_opt_2_1_opt_2[];
extern const GeoLayout sofia_Mouth3_opt_2_1_opt_2[];
extern const GeoLayout sofia_Mouth4_opt_2_1_opt_2[];
extern const GeoLayout sofia_Mouth5_opt_2_1_opt_2[];
extern const GeoLayout sofia_Mouth6_opt_2_1_opt_2[];
extern const GeoLayout sofia_Mouth7_opt_2_1_opt_2[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Left_opt_2[];
extern const GeoLayout sofia_Mouth1_opt_2_8[];
extern const GeoLayout sofia_Mouth2_opt_2_8[];
extern const GeoLayout sofia_Mouth3_opt_2_8[];
extern const GeoLayout sofia_Mouth4_opt_2_8[];
extern const GeoLayout sofia_Mouth5_opt_2_8[];
extern const GeoLayout sofia_Mouth6_opt_2_8[];
extern const GeoLayout sofia_Mouth7_opt_2_8[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Right_opt_2[];
extern const GeoLayout sofia_Mouth1_opt_2_9[];
extern const GeoLayout sofia_Mouth2_opt_2_9[];
extern const GeoLayout sofia_Mouth3_opt_2_9[];
extern const GeoLayout sofia_Mouth4_opt_2_9[];
extern const GeoLayout sofia_Mouth5_opt_2_9[];
extern const GeoLayout sofia_Mouth6_opt_2_9[];
extern const GeoLayout sofia_Mouth7_opt_2_9[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Up_opt_2[];
extern const GeoLayout sofia_Mouth1_opt_2_10[];
extern const GeoLayout sofia_Mouth2_opt_2_10[];
extern const GeoLayout sofia_Mouth3_opt_2_10[];
extern const GeoLayout sofia_Mouth4_opt_2_10[];
extern const GeoLayout sofia_Mouth5_opt_2_10[];
extern const GeoLayout sofia_Mouth6_opt_2_10[];
extern const GeoLayout sofia_Mouth7_opt_2_10[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Down_opt_2[];
extern const GeoLayout sofia_Mouth1_opt_2_11[];
extern const GeoLayout sofia_Mouth2_opt_2_11[];
extern const GeoLayout sofia_Mouth3_opt_2_11[];
extern const GeoLayout sofia_Mouth4_opt_2_11[];
extern const GeoLayout sofia_Mouth5_opt_2_11[];
extern const GeoLayout sofia_Mouth6_opt_2_11[];
extern const GeoLayout sofia_Mouth7_opt_2_11[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Dead_opt_2[];
extern const GeoLayout sofia_geo_opt_2_2_opt_2_opt_1_1[];
extern const GeoLayout sofia_geo_opt_2_2_opt_2_opt_1_2[];
extern const GeoLayout sofia_Left_Hand_Open_opt_2[];
extern const GeoLayout sofia_Left_Hand_Peace_opt_2[];
extern const GeoLayout sofia_Left_Hand_Open_opt_2_1[];
extern const GeoLayout sofia_Right_Hand_Open_opt_2[];
extern const GeoLayout sofia_Right_Hand_Peace_opt_2[];
extern const GeoLayout sofia_Right_Hand_Cap_opt_2[];
extern const GeoLayout sofia_Right_Hand_Wing_Cap_opt_2[];
extern const GeoLayout sofia_geo_opt_2_2[];
extern const GeoLayout sofia_Mouth1_opt_3[];
extern const GeoLayout sofia_Mouth2_opt_3[];
extern const GeoLayout sofia_Mouth3_opt_3[];
extern const GeoLayout sofia_Mouth4_opt_3[];
extern const GeoLayout sofia_Mouth5_opt_3[];
extern const GeoLayout sofia_Mouth6_opt_3[];
extern const GeoLayout sofia_Mouth7_opt_3[];
extern const GeoLayout sofia_Mouth1_opt_3_opt_1[];
extern const GeoLayout sofia_Mouth2_opt_3_opt_1[];
extern const GeoLayout sofia_Mouth3_opt_3_opt_1[];
extern const GeoLayout sofia_Mouth4_opt_3_opt_1[];
extern const GeoLayout sofia_Mouth5_opt_3_opt_1[];
extern const GeoLayout sofia_Mouth6_opt_3_opt_1[];
extern const GeoLayout sofia_Mouth7_opt_3_opt_1[];
extern const GeoLayout sofia_geo_opt_3_opt_3_opt_1[];
extern const GeoLayout sofia_Mouth1_opt_3_opt_2[];
extern const GeoLayout sofia_Mouth2_opt_3_opt_2[];
extern const GeoLayout sofia_Mouth3_opt_3_opt_2[];
extern const GeoLayout sofia_Mouth4_opt_3_opt_2[];
extern const GeoLayout sofia_Mouth5_opt_3_opt_2[];
extern const GeoLayout sofia_Mouth6_opt_3_opt_2[];
extern const GeoLayout sofia_Mouth7_opt_3_opt_2[];
extern const GeoLayout sofia_geo_opt_3_opt_3_opt_2[];
extern const GeoLayout sofia_Head_Left_opt_3[];
extern const GeoLayout sofia_Mouth1_opt_3_1[];
extern const GeoLayout sofia_Mouth2_opt_3_1[];
extern const GeoLayout sofia_Mouth3_opt_3_1[];
extern const GeoLayout sofia_Mouth4_opt_3_1[];
extern const GeoLayout sofia_Mouth5_opt_3_1[];
extern const GeoLayout sofia_Mouth6_opt_3_1[];
extern const GeoLayout sofia_Mouth7_opt_3_1[];
extern const GeoLayout sofia_Head_Right_opt_3[];
extern const GeoLayout sofia_Mouth1_opt_3_2[];
extern const GeoLayout sofia_Mouth2_opt_3_2[];
extern const GeoLayout sofia_Mouth3_opt_3_2[];
extern const GeoLayout sofia_Mouth4_opt_3_2[];
extern const GeoLayout sofia_Mouth5_opt_3_2[];
extern const GeoLayout sofia_Mouth6_opt_3_2[];
extern const GeoLayout sofia_Mouth7_opt_3_2[];
extern const GeoLayout sofia_Head_Up_opt_3[];
extern const GeoLayout sofia_Mouth1_opt_3_3[];
extern const GeoLayout sofia_Mouth2_opt_3_3[];
extern const GeoLayout sofia_Mouth3_opt_3_3[];
extern const GeoLayout sofia_Mouth4_opt_3_3[];
extern const GeoLayout sofia_Mouth5_opt_3_3[];
extern const GeoLayout sofia_Mouth6_opt_3_3[];
extern const GeoLayout sofia_Mouth7_opt_3_3[];
extern const GeoLayout sofia_Head_Down_opt_3[];
extern const GeoLayout sofia_Mouth1_opt_3_4[];
extern const GeoLayout sofia_Mouth2_opt_3_4[];
extern const GeoLayout sofia_Mouth3_opt_3_4[];
extern const GeoLayout sofia_Mouth4_opt_3_4[];
extern const GeoLayout sofia_Mouth5_opt_3_4[];
extern const GeoLayout sofia_Mouth6_opt_3_4[];
extern const GeoLayout sofia_Mouth7_opt_3_4[];
extern const GeoLayout sofia_Head_Dead_opt_3[];
extern const GeoLayout sofia_Capless_Head_opt_3[];
extern const GeoLayout sofia_Mouth1_opt_3_5[];
extern const GeoLayout sofia_Mouth2_opt_3_5[];
extern const GeoLayout sofia_Mouth3_opt_3_5[];
extern const GeoLayout sofia_Mouth4_opt_3_5[];
extern const GeoLayout sofia_Mouth5_opt_3_5[];
extern const GeoLayout sofia_Mouth6_opt_3_5[];
extern const GeoLayout sofia_Mouth7_opt_3_5[];
extern const GeoLayout sofia_geo_opt_1_1_opt_3[];
extern const GeoLayout sofia_Mouth1_opt_1_1_opt_3[];
extern const GeoLayout sofia_Mouth2_opt_1_1_opt_3[];
extern const GeoLayout sofia_Mouth3_opt_1_1_opt_3[];
extern const GeoLayout sofia_Mouth4_opt_1_1_opt_3[];
extern const GeoLayout sofia_Mouth5_opt_1_1_opt_3[];
extern const GeoLayout sofia_Mouth6_opt_1_1_opt_3[];
extern const GeoLayout sofia_Mouth7_opt_1_1_opt_3[];
extern const GeoLayout sofia_geo_opt_2_1_opt_3[];
extern const GeoLayout sofia_Mouth1_opt_2_1_opt_3[];
extern const GeoLayout sofia_Mouth2_opt_2_1_opt_3[];
extern const GeoLayout sofia_Mouth3_opt_2_1_opt_3[];
extern const GeoLayout sofia_Mouth4_opt_2_1_opt_3[];
extern const GeoLayout sofia_Mouth5_opt_2_1_opt_3[];
extern const GeoLayout sofia_Mouth6_opt_2_1_opt_3[];
extern const GeoLayout sofia_Mouth7_opt_2_1_opt_3[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Left_opt_3[];
extern const GeoLayout sofia_Mouth1_opt_3_6[];
extern const GeoLayout sofia_Mouth2_opt_3_6[];
extern const GeoLayout sofia_Mouth3_opt_3_6[];
extern const GeoLayout sofia_Mouth4_opt_3_6[];
extern const GeoLayout sofia_Mouth5_opt_3_6[];
extern const GeoLayout sofia_Mouth6_opt_3_6[];
extern const GeoLayout sofia_Mouth7_opt_3_6[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Right_opt_3[];
extern const GeoLayout sofia_Mouth1_opt_3_7[];
extern const GeoLayout sofia_Mouth2_opt_3_7[];
extern const GeoLayout sofia_Mouth3_opt_3_7[];
extern const GeoLayout sofia_Mouth4_opt_3_7[];
extern const GeoLayout sofia_Mouth5_opt_3_7[];
extern const GeoLayout sofia_Mouth6_opt_3_7[];
extern const GeoLayout sofia_Mouth7_opt_3_7[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Up_opt_3[];
extern const GeoLayout sofia_Mouth1_opt_3_8[];
extern const GeoLayout sofia_Mouth2_opt_3_8[];
extern const GeoLayout sofia_Mouth3_opt_3_8[];
extern const GeoLayout sofia_Mouth4_opt_3_8[];
extern const GeoLayout sofia_Mouth5_opt_3_8[];
extern const GeoLayout sofia_Mouth6_opt_3_8[];
extern const GeoLayout sofia_Mouth7_opt_3_8[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Down_opt_3[];
extern const GeoLayout sofia_Mouth1_opt_3_9[];
extern const GeoLayout sofia_Mouth2_opt_3_9[];
extern const GeoLayout sofia_Mouth3_opt_3_9[];
extern const GeoLayout sofia_Mouth4_opt_3_9[];
extern const GeoLayout sofia_Mouth5_opt_3_9[];
extern const GeoLayout sofia_Mouth6_opt_3_9[];
extern const GeoLayout sofia_Mouth7_opt_3_9[];
extern const GeoLayout sofia_Capless_Head_Switch_Option_Capless_Head_Dead_opt_3[];
extern const GeoLayout sofia_geo_opt_3_opt_3_opt_1_1[];
extern const GeoLayout sofia_geo_opt_3_opt_3_opt_1_2[];
extern const GeoLayout sofia_Left_Hand_Open_opt_3[];
extern const GeoLayout sofia_Left_Hand_Peace_opt_3[];
extern const GeoLayout sofia_Left_Hand_Open_opt_3_1[];
extern const GeoLayout sofia_Right_Hand_Open_opt_3[];
extern const GeoLayout sofia_Right_Hand_Peace_opt_3[];
extern const GeoLayout sofia_Right_Hand_Cap_opt_3[];
extern const GeoLayout sofia_Right_Hand_Wing_Cap_opt_3[];
extern const GeoLayout sofia_geo_opt_3[];
extern const GeoLayout sofia_geo[];
extern Lights1 sofia_Body_lights;
extern Lights1 sofia_Shirt_lights;
extern Lights1 sofia_Skin_lights;
extern Lights1 sofia_Eye_lights;
extern Lights1 sofia_Hair_lights;
extern Lights1 sofia_Hat_lights;
extern Lights1 sofia_Logo_lights;
extern Lights1 sofia_Mouth1_lights;
extern Lights1 sofia_Mouth2_lights;
extern Lights1 sofia_Mouth3_lights;
extern Lights1 sofia_Mouth4_lights;
extern Lights1 sofia_Mouth5_lights;
extern Lights1 sofia_Mouth6_lights;
extern Lights1 sofia_Mouth7_lights;
extern Lights1 sofia_Mouth8_lights;
extern Lights1 sofia_EyeSide_lights;
extern Lights1 sofia_EyeUp_lights;
extern Lights1 sofia_EyeDown_lights;
extern Lights1 sofia_EyeDead_lights;
extern Lights1 sofia_Lines_lights;
extern Lights1 sofia_Shoes_lights;
extern Lights1 sofia_Eye_Half_lights;
extern Lights1 sofia_Eye_Closed_lights;
extern Lights1 sofia_Metal__METAL__lights;
extern u8 sofia_the_line_but_black_rgba16[];
extern u8 sofia_eye1_rgba16[];
extern u8 sofia_hair_ia8[];
extern u8 sofia_capline_ia8[];
extern u8 sofia_caplogo_ci4[];
extern u8 sofia_caplogo_pal_rgba16[];
extern u8 sofia_mouth1_rgba16[];
extern u8 sofia_mouth2_rgba16[];
extern u8 sofia_mouth3_rgba16[];
extern u8 sofia_mouth4_rgba16[];
extern u8 sofia_mouth5_rgba16[];
extern u8 sofia_mouth6_rgba16[];
extern u8 sofia_mouth7_rgba16[];
extern u8 sofia_mouth8_rgba16[];
extern u8 sofia_eye5_rgba16[];
extern u8 sofia_eye6_rgba16[];
extern u8 sofia_eye4_rgba16[];
extern u8 sofia_eye7_rgba16[];
extern u8 sofia_mia_Wing1_rgba16[];
extern u8 sofia_the_line_ia8[];
extern u8 sofia_eye2_rgba16[];
extern u8 sofia_eye3_rgba16[];
extern u8 sofia_mia_Wing2_rgba16[];
extern u8 sofia_metal_mariokart_rgba16[];
extern u8 sofia_Metal_Light_rgba16_rgba16[];
extern Vtx sofia_Butt_mesh_layer_1_vtx_0[14];
extern Gfx sofia_Butt_mesh_layer_1_tri_0[];
extern Vtx sofia_Torso_mesh_layer_1_vtx_0[35];
extern Gfx sofia_Torso_mesh_layer_1_tri_0[];
extern Vtx sofia_Torso_mesh_layer_1_vtx_1[6];
extern Gfx sofia_Torso_mesh_layer_1_tri_1[];
extern Vtx sofia_Head_DL_mesh_layer_1_vtx_0[12];
extern Gfx sofia_Head_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Head_DL_mesh_layer_1_vtx_1[7];
extern Gfx sofia_Head_DL_mesh_layer_1_tri_1[];
extern Vtx sofia_Head_DL_mesh_layer_1_vtx_2[96];
extern Gfx sofia_Head_DL_mesh_layer_1_tri_2[];
extern Vtx sofia_Head_DL_mesh_layer_1_vtx_3[6];
extern Gfx sofia_Head_DL_mesh_layer_1_tri_3[];
extern Vtx sofia_Head_DL_mesh_layer_1_vtx_4[32];
extern Gfx sofia_Head_DL_mesh_layer_1_tri_4[];
extern Vtx sofia_Head_DL_mesh_layer_1_vtx_5[6];
extern Gfx sofia_Head_DL_mesh_layer_1_tri_5[];
extern Vtx sofia_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Mouth_Switch_Option_MouthDL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Mouth_Switch_Option_MouthDL_mesh_layer_1_tri_0[];
extern Vtx sofia_Mouth_Switch_Option_Mouth2DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Mouth_Switch_Option_Mouth2DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Mouth_Switch_Option_Mouth3DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Mouth_Switch_Option_Mouth3DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Mouth_Switch_Option_Mouth4DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Mouth_Switch_Option_Mouth4DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Mouth_Switch_Option_Mouth5DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Mouth_Switch_Option_Mouth5DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Mouth_Switch_Option_Mouth6DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Mouth_Switch_Option_Mouth6DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Mouth_Switch_Option_Mouth7DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Mouth_Switch_Option_Mouth7DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_vtx_0[12];
extern Gfx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_vtx_1[5];
extern Gfx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_tri_1[];
extern Vtx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_vtx_2[5];
extern Gfx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_tri_2[];
extern Vtx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_vtx_3[96];
extern Gfx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_tri_3[];
extern Vtx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_vtx_4[6];
extern Gfx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_tri_4[];
extern Vtx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_vtx_5[32];
extern Gfx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_tri_5[];
extern Vtx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_vtx_6[6];
extern Gfx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_tri_6[];
extern Vtx sofia_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_vtx_0[12];
extern Gfx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_vtx_1[5];
extern Gfx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_tri_1[];
extern Vtx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_vtx_2[5];
extern Gfx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_tri_2[];
extern Vtx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_vtx_3[96];
extern Gfx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_tri_3[];
extern Vtx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_vtx_4[6];
extern Gfx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_tri_4[];
extern Vtx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_vtx_5[32];
extern Gfx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_tri_5[];
extern Vtx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_vtx_6[6];
extern Gfx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_tri_6[];
extern Vtx sofia_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_vtx_0[12];
extern Gfx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_vtx_1[7];
extern Gfx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_tri_1[];
extern Vtx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_vtx_2[96];
extern Gfx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_tri_2[];
extern Vtx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_vtx_3[6];
extern Gfx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_tri_3[];
extern Vtx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_vtx_4[32];
extern Gfx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_tri_4[];
extern Vtx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_vtx_5[6];
extern Gfx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_tri_5[];
extern Vtx sofia_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_vtx_0[12];
extern Gfx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_vtx_1[7];
extern Gfx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_tri_1[];
extern Vtx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_vtx_2[96];
extern Gfx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_tri_2[];
extern Vtx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_vtx_3[6];
extern Gfx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_tri_3[];
extern Vtx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_vtx_4[32];
extern Gfx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_tri_4[];
extern Vtx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_vtx_5[6];
extern Gfx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_tri_5[];
extern Vtx sofia_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_vtx_0[12];
extern Gfx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_vtx_1[7];
extern Gfx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_tri_1[];
extern Vtx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_vtx_2[6];
extern Gfx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_tri_2[];
extern Vtx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_vtx_3[96];
extern Gfx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_tri_3[];
extern Vtx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_vtx_4[6];
extern Gfx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_tri_4[];
extern Vtx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_vtx_5[32];
extern Gfx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_tri_5[];
extern Vtx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_vtx_6[6];
extern Gfx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_tri_6[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_vtx_0[12];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_tri_0[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_vtx_1[7];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_tri_1[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_vtx_2[96];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_tri_2[];
extern Vtx sofia_Capless_Head_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Capless_Head_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_vtx_0[12];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_vtx_1[5];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_tri_1[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_vtx_2[5];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_tri_2[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_vtx_3[96];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_tri_3[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_vtx_0[12];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_vtx_1[5];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_tri_1[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_vtx_2[5];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_tri_2[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_vtx_3[96];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_tri_3[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_vtx_0[12];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_vtx_1[7];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_tri_1[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_vtx_2[96];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_tri_2[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_vtx_0[12];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_vtx_1[7];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_tri_1[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_vtx_2[96];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_tri_2[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1_vtx_0[6];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_vtx_0[12];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_vtx_1[7];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_tri_1[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_vtx_2[6];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_tri_2[];
extern Vtx sofia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_vtx_3[96];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_tri_3[];
extern Vtx sofia_Left_Wing_DL_mesh_layer_4_vtx_0[4];
extern Gfx sofia_Left_Wing_DL_mesh_layer_4_tri_0[];
extern Vtx sofia_Right_Wing_DL_mesh_layer_4_vtx_0[4];
extern Gfx sofia_Right_Wing_DL_mesh_layer_4_tri_0[];
extern Vtx sofia_Left_Arm_Color_mesh_layer_1_vtx_0[9];
extern Gfx sofia_Left_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx sofia_Left_Arm_Color_mesh_layer_1_vtx_1[13];
extern Gfx sofia_Left_Arm_Color_mesh_layer_1_tri_1[];
extern Vtx sofia_Left_Forearm_mesh_layer_1_vtx_0[10];
extern Gfx sofia_Left_Forearm_mesh_layer_1_tri_0[];
extern Vtx sofia_Left_Hand_DL_mesh_layer_1_vtx_0[10];
extern Gfx sofia_Left_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_vtx_0[14];
extern Gfx sofia_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx sofia_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_1_vtx_0[14];
extern Gfx sofia_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_1_tri_0[];
extern Vtx sofia_Right_Arm_Color_mesh_layer_1_vtx_0[9];
extern Gfx sofia_Right_Arm_Color_mesh_layer_1_tri_0[];
extern Vtx sofia_Right_Arm_Color_mesh_layer_1_vtx_1[13];
extern Gfx sofia_Right_Arm_Color_mesh_layer_1_tri_1[];
extern Vtx sofia_Right_Forearm_mesh_layer_1_vtx_0[10];
extern Gfx sofia_Right_Forearm_mesh_layer_1_tri_0[];
extern Vtx sofia_Right_Hand_DL_mesh_layer_1_vtx_0[10];
extern Gfx sofia_Right_Hand_DL_mesh_layer_1_tri_0[];
extern Vtx sofia_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_vtx_0[14];
extern Gfx sofia_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_tri_0[];
extern Vtx sofia_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_vtx_0[14];
extern Gfx sofia_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_tri_0[];
extern Vtx sofia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_vtx_0[10];
extern Gfx sofia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_tri_0[];
extern Vtx sofia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_vtx_1[36];
extern Gfx sofia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_tri_1[];
extern Vtx sofia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_vtx_2[8];
extern Gfx sofia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_tri_2[];
extern Vtx sofia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_vtx_0[10];
extern Gfx sofia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx sofia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_vtx_1[36];
extern Gfx sofia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_tri_1[];
extern Vtx sofia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_vtx_2[8];
extern Gfx sofia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_tri_2[];
extern Vtx sofia_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_vtx_0[8];
extern Gfx sofia_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_tri_0[];
extern Vtx sofia_Left_Thigh_Color_mesh_layer_1_vtx_0[20];
extern Gfx sofia_Left_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx sofia_Left_Thigh_Color_mesh_layer_4_vtx_0[10];
extern Gfx sofia_Left_Thigh_Color_mesh_layer_4_tri_0[];
extern Vtx sofia_Left_Leg_mesh_layer_1_vtx_0[10];
extern Gfx sofia_Left_Leg_mesh_layer_1_tri_0[];
extern Vtx sofia_Left_Shoe_mesh_layer_1_vtx_0[19];
extern Gfx sofia_Left_Shoe_mesh_layer_1_tri_0[];
extern Vtx sofia_Right_Thigh_Color_mesh_layer_1_vtx_0[20];
extern Gfx sofia_Right_Thigh_Color_mesh_layer_1_tri_0[];
extern Vtx sofia_Right_Thigh_Color_mesh_layer_4_vtx_0[10];
extern Gfx sofia_Right_Thigh_Color_mesh_layer_4_tri_0[];
extern Vtx sofia_Right_Leg_mesh_layer_1_vtx_0[10];
extern Gfx sofia_Right_Leg_mesh_layer_1_tri_0[];
extern Vtx sofia_Right_Shoe_DL_mesh_layer_1_vtx_0[19];
extern Gfx sofia_Right_Shoe_DL_mesh_layer_1_tri_0[];
extern Gfx mat_sofia_Body[];
extern Gfx mat_revert_sofia_Body[];
extern Gfx mat_sofia_Shirt[];
extern Gfx mat_revert_sofia_Shirt[];
extern Gfx mat_sofia_Skin[];
extern Gfx mat_revert_sofia_Skin[];
extern Gfx mat_sofia_Eye[];
extern Gfx mat_revert_sofia_Eye[];
extern Gfx mat_sofia_Hair[];
extern Gfx mat_revert_sofia_Hair[];
extern Gfx mat_sofia_Hat[];
extern Gfx mat_revert_sofia_Hat[];
extern Gfx mat_sofia_Logo[];
extern Gfx mat_revert_sofia_Logo[];
extern Gfx mat_sofia_Mouth1[];
extern Gfx mat_revert_sofia_Mouth1[];
extern Gfx mat_sofia_Mouth2[];
extern Gfx mat_revert_sofia_Mouth2[];
extern Gfx mat_sofia_Mouth3[];
extern Gfx mat_revert_sofia_Mouth3[];
extern Gfx mat_sofia_Mouth4[];
extern Gfx mat_revert_sofia_Mouth4[];
extern Gfx mat_sofia_Mouth5[];
extern Gfx mat_revert_sofia_Mouth5[];
extern Gfx mat_sofia_Mouth6[];
extern Gfx mat_revert_sofia_Mouth6[];
extern Gfx mat_sofia_Mouth7[];
extern Gfx mat_revert_sofia_Mouth7[];
extern Gfx mat_sofia_Mouth8[];
extern Gfx mat_revert_sofia_Mouth8[];
extern Gfx mat_sofia_EyeSide[];
extern Gfx mat_revert_sofia_EyeSide[];
extern Gfx mat_sofia_EyeUp[];
extern Gfx mat_revert_sofia_EyeUp[];
extern Gfx mat_sofia_EyeDown[];
extern Gfx mat_revert_sofia_EyeDown[];
extern Gfx mat_sofia_EyeDead[];
extern Gfx mat_revert_sofia_EyeDead[];
extern Gfx mat_sofia_Wings[];
extern Gfx mat_revert_sofia_Wings[];
extern Gfx mat_sofia_Lines[];
extern Gfx mat_revert_sofia_Lines[];
extern Gfx mat_sofia_Shoes[];
extern Gfx mat_revert_sofia_Shoes[];
extern Gfx mat_sofia_Eye_Half[];
extern Gfx mat_revert_sofia_Eye_Half[];
extern Gfx mat_sofia_Eye_Closed[];
extern Gfx mat_revert_sofia_Eye_Closed[];
extern Gfx mat_sofia_Wings2[];
extern Gfx mat_revert_sofia_Wings2[];
extern Gfx mat_sofia_Metal__METAL_[];
extern Gfx mat_revert_sofia_Metal__METAL_[];
extern Gfx sofia_Butt_mesh_layer_1[];
extern Gfx sofia_Butt_mesh_layer_1_opt_2[];
extern Gfx sofia_Torso_mesh_layer_1[];
extern Gfx sofia_Torso_mesh_layer_1_opt_2[];
extern Gfx sofia_Head_DL_mesh_layer_1[];
extern Gfx sofia_Head_DL_mesh_layer_1_opt_1[];
extern Gfx sofia_Head_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Head_DL_mesh_layer_1_opt_2_0[];
extern Gfx sofia_Mouth_DL_mesh_layer_1[];
extern Gfx sofia_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Mouth_Switch_Option_MouthDL_mesh_layer_1[];
extern Gfx sofia_Mouth_Switch_Option_MouthDL_mesh_layer_1_opt_2[];
extern Gfx sofia_Mouth_Switch_Option_Mouth2DL_mesh_layer_1[];
extern Gfx sofia_Mouth_Switch_Option_Mouth2DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Mouth_Switch_Option_Mouth3DL_mesh_layer_1[];
extern Gfx sofia_Mouth_Switch_Option_Mouth3DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Mouth_Switch_Option_Mouth4DL_mesh_layer_1[];
extern Gfx sofia_Mouth_Switch_Option_Mouth4DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Mouth_Switch_Option_Mouth5DL_mesh_layer_1[];
extern Gfx sofia_Mouth_Switch_Option_Mouth5DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Mouth_Switch_Option_Mouth6DL_mesh_layer_1[];
extern Gfx sofia_Mouth_Switch_Option_Mouth6DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Mouth_Switch_Option_Mouth7DL_mesh_layer_1[];
extern Gfx sofia_Mouth_Switch_Option_Mouth7DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1[];
extern Gfx sofia_Head_Left_Switch_Option_Head_Left_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx sofia_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1[];
extern Gfx sofia_Head_Right_Switch_Option_Head_Right_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx sofia_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1[];
extern Gfx sofia_Head_Up_Switch_Option_Head_Up_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx sofia_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1[];
extern Gfx sofia_Head_Down_Switch_Option_Head_Down_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx sofia_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1[];
extern Gfx sofia_Head_Dead_Switch_Option_Head_Dead_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_opt_1[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_opt_2[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_opt_2_0[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_opt_2_1[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1_opt_2_2[];
extern Gfx sofia_Capless_Head_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx sofia_Capless_Head_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Capless_Head_Left_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Left_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Capless_Head_Right_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Right_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Capless_Head_Up_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Up_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Capless_Head_Down_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Down_Switch_Option_Mouth_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1[];
extern Gfx sofia_Capless_Head_Switch_Option_Capless_Head_Dead_Switch_Option_Capless_Head_Dead_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Left_Wing_DL_mesh_layer_4[];
extern Gfx sofia_Left_Wing_DL_mesh_layer_4_opt_1[];
extern Gfx sofia_Left_Wing_DL_mesh_layer_4_opt_2[];
extern Gfx sofia_Right_Wing_DL_mesh_layer_4[];
extern Gfx sofia_Right_Wing_DL_mesh_layer_4_opt_1[];
extern Gfx sofia_Right_Wing_DL_mesh_layer_4_opt_2[];
extern Gfx sofia_Left_Arm_Color_mesh_layer_1[];
extern Gfx sofia_Left_Arm_Color_mesh_layer_1_opt_2[];
extern Gfx sofia_Left_Forearm_mesh_layer_1[];
extern Gfx sofia_Left_Forearm_mesh_layer_1_opt_2[];
extern Gfx sofia_Left_Hand_DL_mesh_layer_1[];
extern Gfx sofia_Left_Hand_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1[];
extern Gfx sofia_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1_opt_2[];
extern Gfx sofia_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_1[];
extern Gfx sofia_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_1_opt_2[];
extern Gfx sofia_Right_Arm_Color_mesh_layer_1[];
extern Gfx sofia_Right_Arm_Color_mesh_layer_1_opt_2[];
extern Gfx sofia_Right_Forearm_mesh_layer_1[];
extern Gfx sofia_Right_Forearm_mesh_layer_1_opt_2[];
extern Gfx sofia_Right_Hand_DL_mesh_layer_1[];
extern Gfx sofia_Right_Hand_DL_mesh_layer_1_opt_2[];
extern Gfx sofia_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1[];
extern Gfx sofia_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_opt_2[];
extern Gfx sofia_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1[];
extern Gfx sofia_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1_opt_2[];
extern Gfx sofia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1[];
extern Gfx sofia_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1_opt_2[];
extern Gfx sofia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1[];
extern Gfx sofia_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1_opt_2[];
extern Gfx sofia_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4[];
extern Gfx sofia_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_opt_2[];
extern Gfx sofia_Left_Thigh_Color_mesh_layer_1[];
extern Gfx sofia_Left_Thigh_Color_mesh_layer_1_opt_2[];
extern Gfx sofia_Left_Thigh_Color_mesh_layer_4[];
extern Gfx sofia_Left_Thigh_Color_mesh_layer_4_opt_2[];
extern Gfx sofia_Left_Leg_mesh_layer_1[];
extern Gfx sofia_Left_Leg_mesh_layer_1_opt_2[];
extern Gfx sofia_Left_Shoe_mesh_layer_1[];
extern Gfx sofia_Left_Shoe_mesh_layer_1_opt_2[];
extern Gfx sofia_Right_Thigh_Color_mesh_layer_1[];
extern Gfx sofia_Right_Thigh_Color_mesh_layer_1_opt_2[];
extern Gfx sofia_Right_Thigh_Color_mesh_layer_4[];
extern Gfx sofia_Right_Thigh_Color_mesh_layer_4_opt_2[];
extern Gfx sofia_Right_Thigh_Color_mesh_layer_4_with_layer_4_revert[];
extern Gfx sofia_Right_Thigh_Color_mesh_layer_4_opt_2_with_layer_4_revert[];
extern Gfx sofia_Right_Leg_mesh_layer_1[];
extern Gfx sofia_Right_Leg_mesh_layer_1_opt_2[];
extern Gfx sofia_Right_Shoe_DL_mesh_layer_1_with_layer_1_revert[];
extern Gfx sofia_Right_Shoe_DL_mesh_layer_1_opt_2_with_layer_1_revert[];
extern Gfx sofia_Right_Shoe_DL_mesh_layer_1_with_layer_5_revert[];
